(function(){
'use strict';
function $(id){return document.getElementById(id)}
var screens={menu:$('menuScreen'),game:$('gameScreen'),qresult:$('questionResultScreen'),summary:$('summaryScreen')};
var H=$('h'),S=$('s'),L=$('l'),targetEl=$('target'),guessEl=$('guess'),sTrack=$('sTrack'),lTrack=$('lTrack');
var mode='easy',question=0,target={h:0,s:0,l:50},results=[],lastResult=null;
function clamp(n,a,b){return Math.min(b,Math.max(a,n))}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function hslCss(c){return 'hsl('+c.h+', '+c.s+'%, '+c.l+'%)'}
function show(name){Object.keys(screens).forEach(function(k){screens[k].classList.toggle('active',k===name)})}
function bestKey(){return 'hsl-trainer-best-'+mode}
function readStore(key){try{return localStorage.getItem(key)}catch(e){return null}}
function writeStore(key,value){try{localStorage.setItem(key,value)}catch(e){}}
function getBest(m){var n=parseInt(readStore('hsl-trainer-best-'+m)||'0',10);return isNaN(n)?0:n}
function updateMenuBest(){var e=getBest('easy'),n=getBest('normal');$('easyBest').textContent=e?'ベスト '+e:'ベスト —';$('normalBest').textContent=n?'ベスト '+n:'ベスト —'}
function getGuess(){return {h:parseInt(H.value,10),s:parseInt(S.value,10),l:parseInt(L.value,10)}}
function paint(){var g=getGuess();guessEl.style.backgroundColor=hslCss(g);$('hv').textContent=g.h+'°';$('sv').textContent=g.s+'%';$('lv').textContent=g.l+'%';sTrack.style.setProperty('--track','linear-gradient(90deg,hsl('+g.h+',0%,'+g.l+'%),hsl('+g.h+',100%,'+g.l+'%))');lTrack.style.setProperty('--track','linear-gradient(90deg,hsl('+g.h+','+g.s+'%,0%),hsl('+g.h+','+g.s+'%,50%),hsl('+g.h+','+g.s+'%,100%))')}
function runningTotal(){return results.reduce(function(a,r){return a+r.score},0)}
function renderProgress(){var box=$('progressDots');box.innerHTML='';for(var i=0;i<5;i++){var d=document.createElement('span');d.className='dot'+(i<question?' done':'')+(i===question?' current':'');box.appendChild(d)}$('runningTotal').textContent=runningTotal()+' pt'}
function configureMode(){var easy=mode==='easy';$('modePill').textContent=easy?'イージー':'ノーマル';$('lRow').classList.toggle('locked',easy);$('lockNote').textContent=easy?'固定':'';$('lCompareRow').style.display=easy?'none':'grid'}
function newQuestion(){if(question>=5){showSummary();return}target={h:rand(0,359),s:rand(25,95),l:rand(30,70)};H.value=rand(0,359);S.value=rand(20,80);L.value=mode==='easy'?target.l:rand(25,75);targetEl.style.backgroundColor=hslCss(target);paint();renderProgress();show('game')}
function startSession(m){mode=m;question=0;results=[];lastResult=null;configureMode();newQuestion()}
function stepValue(id,dir){var r=$(id),v=parseInt(r.value,10)+dir;if(id==='h'){if(v<0)v=359;if(v>359)v=0}else{v=clamp(v,0,100)}r.value=v;paint()}
function hslToRgb(c){var h=((c.h%360)+360)%360,s=c.s/100,l=c.l/100,cc=(1-Math.abs(2*l-1))*s,x=cc*(1-Math.abs((h/60)%2-1)),m=l-cc/2,r=0,g=0,b=0;if(h<60){r=cc;g=x}else if(h<120){r=x;g=cc}else if(h<180){g=cc;b=x}else if(h<240){g=x;b=cc}else if(h<300){r=x;b=cc}else{r=cc;b=x}return[r+m,g+m,b+m]}
function rgbToLab(rgb){function lin(v){return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}var r=lin(rgb[0]),g=lin(rgb[1]),b=lin(rgb[2]);var x=(r*.4124564+g*.3575761+b*.1804375)/.95047,y=r*.2126729+g*.7151522+b*.072175,z=(r*.0193339+g*.119192+b*.9503041)/1.08883;function f(t){return t>216/24389?Math.cbrt(t):(24389/27*t+16)/116}var fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
function deltaE00(a,b){var L1=a[0],a1=a[1],b1=a[2],L2=b[0],a2=b[1],b2=b[2];var C1=Math.hypot(a1,b1),C2=Math.hypot(a2,b2),Cb=(C1+C2)/2,G=.5*(1-Math.sqrt(Math.pow(Cb,7)/(Math.pow(Cb,7)+Math.pow(25,7))));var a1p=(1+G)*a1,a2p=(1+G)*a2,C1p=Math.hypot(a1p,b1),C2p=Math.hypot(a2p,b2);function hp(x,y){var h=Math.atan2(y,x)*180/Math.PI;return h<0?h+360:h}var h1=hp(a1p,b1),h2=hp(a2p,b2),dL=L2-L1,dC=C2p-C1p,dh;if(C1p*C2p===0)dh=0;else if(Math.abs(h2-h1)<=180)dh=h2-h1;else dh=h2-h1>180?h2-h1-360:h2-h1+360;var dH=2*Math.sqrt(C1p*C2p)*Math.sin(dh*Math.PI/360),Lb=(L1+L2)/2,Cbp=(C1p+C2p)/2,hb;if(C1p*C2p===0)hb=h1+h2;else if(Math.abs(h1-h2)<=180)hb=(h1+h2)/2;else hb=h1+h2<360?(h1+h2+360)/2:(h1+h2-360)/2;var T=1-.17*Math.cos((hb-30)*Math.PI/180)+.24*Math.cos(2*hb*Math.PI/180)+.32*Math.cos((3*hb+6)*Math.PI/180)-.2*Math.cos((4*hb-63)*Math.PI/180),dt=30*Math.exp(-Math.pow((hb-275)/25,2)),Rc=2*Math.sqrt(Math.pow(Cbp,7)/(Math.pow(Cbp,7)+Math.pow(25,7))),Sl=1+.015*Math.pow(Lb-50,2)/Math.sqrt(20+Math.pow(Lb-50,2)),Sc=1+.045*Cbp,Sh=1+.015*Cbp*T,Rt=-Math.sin(2*dt*Math.PI/180)*Rc,x=dL/Sl,y=dC/Sc,z=dH/Sh;return Math.sqrt(x*x+y*y+z*z+Rt*y*z)}
function colorDelta(t,g){return deltaE00(rgbToLab(hslToRgb(t)),rgbToLab(hslToRgb(g)))}
function scoreFromDelta(d){return clamp(Math.round(100*Math.exp(-Math.pow(d/11.5,1.28))),0,100)}
function grade(score){if(score>=95)return'S';if(score>=85)return'A';if(score>=70)return'B';if(score>=55)return'C';return'D'}
function hueDiff(a,b){var d=b-a;while(d>180)d-=360;while(d<-180)d+=360;return d}
function signed(n,suffix){return(n>0?'+':'')+n+suffix}
function judge(){var g=getGuess(),d=colorDelta(target,g),score=scoreFromDelta(d),gr=grade(score);lastResult={target:{h:target.h,s:target.s,l:target.l},guess:g,delta:d,score:score,grade:gr};results.push(lastResult);renderQuestionResult(lastResult);show('qresult')}
function pct(v,max){return clamp(v/max*100,0,100)+'%'}
function renderQuestionResult(r){var badge=$('gradeBadge');badge.textContent=r.grade;badge.className='grade-badge '+r.grade.toLowerCase();$('questionScore').textContent=r.score;$('deltaText').textContent='ΔE '+r.delta.toFixed(1);$('resultTargetColor').style.backgroundColor=hslCss(r.target);$('resultGuessColor').style.backgroundColor=hslCss(r.guess);$('hg').style.left=pct(r.guess.h,359);$('ht').style.left=pct(r.target.h,359);$('sg').style.left=pct(r.guess.s,100);$('st').style.left=pct(r.target.s,100);$('lg').style.left=pct(r.guess.l,100);$('lt').style.left=pct(r.target.l,100);$('hdiff').textContent=signed(hueDiff(r.target.h,r.guess.h),'°');$('sdiff').textContent=signed(r.guess.s-r.target.s,'%');$('ldiff').textContent=signed(r.guess.l-r.target.l,'%');$('sCompare').style.setProperty('--sat-track','linear-gradient(90deg,hsl('+r.target.h+',0%,'+r.target.l+'%),hsl('+r.target.h+',100%,'+r.target.l+'%))');$('lCompare').style.setProperty('--light-track','linear-gradient(90deg,hsl('+r.target.h+','+r.target.s+'%,0%),hsl('+r.target.h+','+r.target.s+'%,50%),hsl('+r.target.h+','+r.target.s+'%,100%))');$('exactValues').innerHTML='ターゲット H '+r.target.h+'° / S '+r.target.s+'% / L '+r.target.l+'%<br>あなたの色 H '+r.guess.h+'° / S '+r.guess.s+'% / L '+r.guess.l+'%';$('nextBtn').textContent=question===4?'結果を見る':'次の問題'}
function nextQuestion(){question+=1;newQuestion()}
function showSummary(){var total=runningTotal(),avg=results.reduce(function(a,r){return a+r.delta},0)/results.length,oldBest=getBest(mode),isRecord=total>oldBest;if(isRecord)writeStore(bestKey(),String(total));var best=Math.max(oldBest,total);$('summaryMode').textContent=mode==='easy'?'イージー':'ノーマル';$('totalScore').textContent=total;$('summaryMeta').textContent='平均 ΔE '+avg.toFixed(1)+' / ベスト '+best;$('recordBadge').classList.toggle('show',isRecord);var list=$('roundList');list.innerHTML='';results.forEach(function(r,i){var row=document.createElement('div');row.className='round-item';row.innerHTML='<div>Q'+(i+1)+'</div><div class="mini-swatch"><span style="background:'+hslCss(r.target)+'"></span><span style="background:'+hslCss(r.guess)+'"></span></div><div class="round-grade" style="color:'+(r.grade==='S'?'var(--yellow)':r.grade==='A'?'var(--green)':r.grade==='B'?'var(--blue)':'var(--muted)')+'">'+r.grade+'</div><div class="round-score">'+r.score+' pt</div><div class="round-de">ΔE '+r.delta.toFixed(1)+'</div>';list.appendChild(row)});updateMenuBest();show('summary')}
[H,S,L].forEach(function(r){r.addEventListener('input',paint,{passive:true})});document.querySelectorAll('.step').forEach(function(btn){btn.addEventListener('click',function(){if(mode==='easy'&&btn.dataset.for==='l')return;stepValue(btn.dataset.for,parseInt(btn.dataset.dir,10))})});document.querySelectorAll('.mode-card').forEach(function(btn){btn.addEventListener('click',function(){startSession(btn.dataset.mode)})});$('judgeBtn').addEventListener('click',judge);$('nextBtn').addEventListener('click',nextQuestion);$('retryBtn').addEventListener('click',function(){startSession(mode)});$('modeSelectBtn').addEventListener('click',function(){updateMenuBest();show('menu')});document.addEventListener('touchmove',function(e){if(!e.target.closest('.range')&&!e.target.closest('.summary-shell')&&!e.target.closest('.result-wrap'))e.preventDefault()},{passive:false});
updateMenuBest();
})();
